name: Build and Upload to TestPyPI

on:
  push:
      branches: [ main ]
      
  workflow_dispatch:
  
jobs:

  build:
      runs-on: windows-latest
      
      
    steps:
      - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
                - name: Installs and Upgrades PIP and Other Dependencies
                        run: |
                                  python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                    
                          - name: Build and Upload to TestPyPI
                          
        run: |
          python setup.py sdist bdist_wheel
                    python -m twine upload dist/*
                            env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
                    TWINE_REPOSITORY: testpypi
                      
